# Generated by Django 5.2.15 on 2026-06-13 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salat', models.CharField(choices=[('Fajr', 'Fajr'), ('Dhuhr', 'Dhuhr'), ('Asr', 'Asr'), ('Maghrib', 'Maghrib'), ('Isha', 'Isha')], max_length=100)),
                ('on_time', models.BooleanField()),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
